### ISSUE TITLE
Priority Tag saved as tags. After rebooting, it is created as a tag. getPriority will return the default of LOW

### ISSUE THREAD

**Issue by pzhengze** [AY2223S2-CS2103T-T12-1/tp#152]
Priority Tag to be implemented as not a Tag / Displayed and saved separate from other tags.

**Comment by euph00** [comment]
I would recommend saving as a separate form of tag different from other tags because then the implementation just needs to copy and adapt the current tag saving mechanism in storage, rather than implement a whole new system

**Comment by pzhengze** [comment]
Can be saved just as a field like the rest so there is no need for a new JsonAdaptable

**Comment by pzhengze** [comment]
I've been the one handling storage so I can handle this.
