### ISSUE TITLE
Role Tags gets overridden by Edit Command.

### ISSUE THREAD

**Issue by pzhengze** [AY2223S2-CS2103T-T12-1/tp#153]
To implement Role Tags as non-Tags / Saved and Displayed separate from normal tags.

**Comment by euph00** [comment]
Can you elaborate what it means to be overridden

**Comment by pzhengze** [comment]
Our current display of the role tags is displaying them placing them together with other misc tags. When we use edit command to edit tags, it removes the displayed role tags as well. Role tag variable in patient or staff remains unchanged.

**Comment by euph00** [comment]
Got it, was just able to reproduce the issue

**Comment by pzhengze** [comment]
Should be an easy fix to display the role tag separately from normal tags.

**Comment by euph00** [comment]
> Should be an easy fix to display the role tag separately from normal tags.

Would that not just be a UI fix? I reckon there would need to be a change in the way roletag is stored in person objects

**Comment by pzhengze** [comment]
Yep simplest solution is just a ui fix. Need to remove some logic components to stop adding the role tag to normal tag set though.
