### ISSUE TITLE
As a ward doctor getting ready for shift, I want to add and delete events from my personal duty schedule

### ISSUE THREAD

**Issue by euph00** [AY2223S2-CS2103T-T12-1/tp#17]
So that I can track my schedule from the centralized system and easily access records of patients as I check my schedule

**Comment by euph00** [comment]
This is unlikely to implement as it lies outside of core set of features which is managing patients/wards/staff allocation.

**Comment by pzhengze** [comment]
Not implementing due to time constraints.
