### ISSUE TITLE
[PE-D][Tester A] priority was stated to be not case sensitive

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-T12-1/tp#179]
As stated in the UG, priority is not case-sensitive. Entering "Low" for priority results in an error thrown stating invalid arguments.
Other than this, priority seems to be working fine!

![image.png](https://raw.githubusercontent.com/amoonguss1/ped/main/files/dddcc3f4-e78e-4932-9b8b-59186e24c7ff.png)

![image.png](https://raw.githubusercontent.com/amoonguss1/ped/main/files/d561ec29-ba6b-4c14-b45b-b7a463daa5fb.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: amoonguss1/ped#9

**Comment by euph00** [comment]
UG bug. Please note that you need an escape character or 2 newlines to have a newline in markdown. "`ID_NUMBER` shoul..." should start on a new line, and the line describing `PRIORITY` should correctly state specification for this feature.

**Comment by euph00** [comment]
this is related to #159
