### ISSUE TITLE
As a ward nurse/doctor moving a patient, I want to view important notes about a patient, such as being a fall risk etc.

### ISSUE THREAD

**Issue by euph00** [AY2223S2-CS2103T-T12-1/tp#26]
So that I can be reminded about each patient's unique needs without having to dig through records

**Comment by euph00** [comment]
This is not essential as this can technically be satisfied by the patient's full details sections, albeit less conveniently

**Comment by pzhengze** [comment]
Not implementing. Fulfilled by view command.
