### ISSUE TITLE
Implement functionality: UI with regards to ward

### ISSUE THREAD

**Issue by euph00** [AY2223S2-CS2103T-T12-1/tp#41]
This issue tracks the implementation of displaying information on the UI with regards to wards (refer to UG for `lsward`, `lspat w/WARD_NAME` commands etc.). Implement UI support for logic issues #38.

**Comment by jinnieshin** [comment]
Is this issue the same as #32 ?

**Comment by euph00** [comment]
Not quite, when I first created this it was a bit more general than #32. But at this point I think we can link them because lsward should be the last thing related to wards not yet implemented
