### ISSUE TITLE
add command saves address with tag behind it

### ISSUE THREAD

**Issue by jinnieshin** [AY2223S2-CS2103T-T12-1/tp#89]
<img width="151" alt="Screenshot 2023-03-21 at 9 56 20 PM" src="https://user-images.githubusercontent.com/31308772/226628245-714d8925-a495-4416-9864-7f3c4015bc40.png">

**Comment by pzhengze** [comment]
Hi do you recall what was the command you used to do this? I can't seem to reproduce it

**Comment by jinnieshin** [comment]
I used "add n/temp name id/12345 p/12345678 e/temp@gmail.com a/temp [t/Patient]"

**Comment by pzhengze** [comment]
The square brackets in the user guide are meant to signify optional parameters. You're not supposed to have the square bracket when actually running the command.

**Comment by pzhengze** [comment]
[Quote from UG](https://github.com/AY2223S2-CS2103T-T12-1/tp/blob/master/docs/UserGuide.md#notes-about-formatting): 
> Items in square brackets are optional parameters, e.g. addpat n/NAME [t/TAG] can be used as addpat n/John Doe t/urgent or simply as addpat n/John Doe

**Comment by jinnieshin** [comment]
Oh okay thanks. Its weird that the tag is given properly even in such cases.
